export { default as Header } from "./Header"
export { default as Nav } from "./Nav"
export { default as NavAdm } from "./NavAdm"
export { default as Main } from "./Main"
export { default as Footer } from "./Footer"
export { default as Loading } from "./Loading"
export { default as AjudeMain } from "./AjudeMain"
export { default as AdoMain } from "./AdoMain"